### PR TITLE
Add Model Version Creation Features

### PR DESCRIPTION
**Pull request by StephenODea54**
Ref #2 

Adds the following features to the create model versioning page:
- Adds in notifications based on the success / failure of provisioning the model version.
- Added a loading spinner to improve the loading UX

Also added the following changes:
- Added a `forwardRef` to the text area component. Apparently the form will not pick up on any changes in the text area component without a ref.
- Added a dummy upload artifacts route. One, because we need it eventually. Two, because the success notification of the create model version will have a link for the user to directly navigate to this page.
- Fixed some of the TypeScript types for the ML Model and ML Model Versioning such that it reflects the most recent changes made on the server.

image

### CODE REVIEW

**Comment by wetherc** [comment]
Dumb Q - why show a toast and not just auto-redirect the user to the Upload Artifacts page?

**Comment by StephenODea54** [comment]
> Dumb Q - why show a toast and not just auto-redirect the user to the Upload Artifacts page?

We can get rid of the toast for the success and auto-redirect. I didn't want the user to have the impression of "you must submit your stuff right this instance". Just trying to enforce the notion that you can upload artifacts at any time as long as the model is not archived or published.

**Comment by wetherc** [comment]
Ohhhh gotcha gotcha. Is there a model version detail page? Could direct there to show, "Hey, look! Here's the thing you just made!" With an "Upload Files" button somewhere on the page

**Comment by StephenODea54** [comment]
> Ohhhh gotcha gotcha. Is there a model version detail page? Could direct there to show, "Hey, look! Here's the thing you just made!" With an "Upload Files" button somewhere on the page

Not yet but I was thinking there would be. I was thinking that could be the place where we show the file browser for the stuff uploaded to the storage provider.

But yeah we can do that! I'm still going to keep the toast for the error.

**Comment by wetherc** [comment]
Okie doke sounds good to me!

**Review by wetherc — APPROVED** [review]

**Pull request merged**
