### PR TITLE
Add Register Functionality

### PR DESCRIPTION
**Pull request by StephenODea54**
Ref #15 

Adds route for users to register an account. Upon completion, a notification is displayed letting the user know that a verification email has been sent to their email address. Obviously, this is not actually implemented yet.

### CODE REVIEW

**Review by wetherc — APPROVED** [review]
Are we able to auto-login after account creation? Hit the /login endpoint behind the scenes on the user's behalf to get an initial token?

**Comment by StephenODea54** [comment]
> Are we able to auto-login after account creation? Hit the /login endpoint behind the scenes on the user's behalf to get an initial token?

Yeah we can do that. We'll want to (as I'm sure you're aware) revisit restrictions for non-verified users in the future.

**Comment by wetherc** [comment]
Hundred percent, I'm thinking of just adding an isVerified flag to the Pothos auth stuff and gating most API mutations and queries behind that

**Comment by StephenODea54** [comment]
Okay sick that sounds good!

**Pull request merged**
